- name: Create filebrowser database folder
  file:
    state: directory
    path: "{{ file_browser_db_path }}"
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Check if a database already exists
  stat:
    path: "{{ file_browser_db_path }}/filebrowser.db"
  register: file_browser_db

- name: Copy filebrowser database
  copy:
    src: filebrowser_database.db
    dest: "{{ file_browser_db_path }}/filebrowser.db"
    owner: "{{ ansible_user }}"
    mode: '0755'
  when: not file_browser_db.stat.exists

- name: Create filebrowser configuration folder
  file:
    state: directory
    path: "{{ file_browser_config_path }}"
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Check if a configuration already exists
  stat:
    path: "{{ file_browser_config_path }}/settings.json"
  register: file_browser_config

- name: Copy filebrowser configuration
  copy:
    src: filebrowser_config_settings.json
    dest: "{{ file_browser_config_path }}/settings.json"
    owner: "{{ ansible_user }}"
    mode: '0755'
  when: not file_browser_config.stat.exists