- name: Create deploy folder
  file:
    path: "{{ maintenance_station_deploy_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Create configuration folder
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - { name: "filebrowser", path: "{{ file_browser_db_path }}" }
    - { name: "heimdall", path: "{{ heimdall_config_path }}" }
    - { name: "semaphore", path: "{{ semaphore_config_path }}" }
    - { name: "jenkins", path: "{{ jenkins_config_path }}" }

- name: Filebrowser tasks
  include_tasks: filebrowser.yml

- name: Semaphore tasks
  include_tasks: semaphore.yml

- name: Copy docker compose file
  template:
    src:  docker_compose.yml.j2
    dest: "{{ maintenance_station_deploy_path }}/docker-compose.yml"
    mode: '0755'

- name: Compose deploy
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ maintenance_station_deploy_path }}/"