- name: Create deploy folder
  file:
    path: "{{ maintenance_station_deploy_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Filebrowser tasks
  include_tasks: filebrowser.yml

- name: Copy docker compose file
  template:
    src:  docker_compose.yml.j2
    dest: "{{ maintenance_station_deploy_path }}/docker-compose.yml"
    mode: '0755'

- name: Compose deploy
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ maintenance_station_deploy_path }}/"