ispy_deploy_path: /DATA/AppData/ispy-agentdvr

ispy_agentdvr_vers: 7.3.7.0

ispy_agentdvr_encoding_enable: true

ispy_agentdvr_config_path: "{{ ispy_deploy_path }}/config"
ispy_agentdvr_recorings_path: "{{ ispy_deploy_path }}/recordings"
ispy_agentdvr_models_path: "{{ ispy_deploy_path }}/models"
ispy_agentdvr_commands_path: "{{ ispy_deploy_path }}/commands"

ispy_agentdvr_webui_port: 8090
ispy_agentdvr_udp_port: 3478
ispy_agentdvr_webrtc_ports: 50000-50100