- name: Create deploy folder
  file: 
    path: "{{ download_station_deploy_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Create configuration folder
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - { name: "pyload", path: "{{ pyload_config_path }}" }
    - { name: "radarr", path: "{{ radarr_config_path }}" }
    - { name: "jackett", path: "{{ jackett_config_path }}" }
    - { name: "amule", path: "{{ amule_config_path }}" }
    - { name: "plex", path: "{{ plex_config_library_path }}" }
    - { name: "transmission", path: "{{ transmission_config_path }}" }

- name: Plex tasks
  include_tasks: plex.yml

- name: Transmission tasks
  include_tasks: transmission.yml

- name: Copy docker compose file
  template:
    src:  docker_compose.yml.j2
    dest: "{{ download_station_deploy_path }}/docker-compose.yml"
    mode: '0755'

- name: Compose deploy
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ download_station_deploy_path }}/"