- name: Deploy infrastracture for synology nas
  gather_facts: false
  hosts:
    - nas
  vars_files:
    - vars/vars.yml
    - vars/vault_vars.yml
  roles:
    - docker-station
    - download-station
    - maintenance-station
