- name: Deploy infrastracture for synology nas
  gather_facts: false
  hosts:
    - nas
  vars_files:
    - vars/vars.yml
    - vars/vault_vars.yml
  roles:
    - role: docker-station
      tags: docker-station
    - role: download-station
      tags: download-station
    - role: maintenance-station
      tags: maintenance-station
