- name: Create deploy folder
  file:
    path: "{{ portainer_deploy_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy docker compose file
  template:
    src:  docker_compose.yml.j2
    dest: "{{ portainer_deploy_path }}/docker-compose.yml"
    mode: '0755'

- name: Create certs folder
  file:
    path: "{{ portainer_deploy_path }}/certs"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy cert files
  copy:
    src: "certs/{{ item }}"
    dest: "{{ portainer_deploy_path }}/certs/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - synology-nas.home.crt
    - synology-nas.home.key