- name: Create deploy folder
  file:
    path: "{{ surveillance_deploy_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Create agentdvr dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - { name: "ispy_agentdvr_config_path", path: "{{ ispy_agentdvr_config_path }}" }
    - { name: "ispy_agentdvr_recorings_path", path: "{{ ispy_agentdvr_recorings_path }}" }
    - { name: "ispy_agentdvr_models_path", path: "{{ ispy_agentdvr_models_path }}" }
    - { name: "ispy_agentdvr_commands_path", path: "{{ ispy_agentdvr_commands_path }}" }

- name: Copy docker compose file
  template:
    src:  docker_compose.yml.j2
    dest: "{{ surveillance_deploy_path }}/docker-compose.yml"
    mode: '0755'

- name: Compose deploy
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ surveillance_deploy_path }}/"

